### ISSUE TITLE
No error, but no color?

### ISSUE THREAD

**Issue by KyleKing** [nooitaf/meteor-colors#2]
I added your package then loaded in the sample code:

```JS
if (Meteor.isServer) {
	//server
	console.log('red'.red)
	console.log('green'.green)
	console.log('blue'.blue)
	console.log('~~~~~~'.grey)
	console.log('R'.red + 'G'.green + 'B'.blue)
	console.log('~~~~~~'.grey)
	var test = 'ALLTHECOLORS';
	console.log(test.rainbow);
}
```

But no colors, only white? I've used colors.js in another Node.js project, so I don't think it is my terminal.

<img width="318" alt="nooitaf-meteor-colors add colors to strings google chrome today at 7 31 49 pm" src="https://cloud.githubusercontent.com/assets/3784339/13383117/47f13c72-de52-11e5-93e0-2d4e0e7dce1b.png">

Update: I did get an error. I tried adding the set themes and it turns out that ```colors``` is not defined?
```
W20160228-19:37:00.244(-5)? (STDERR) TypeError: Cannot call method 'setTheme' of undefined
W20160228-19:37:00.245(-5)? (STDERR)     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/app/server/colors.js:9:8
W20160228-19:37:00.245(-5)? (STDERR)     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/app/server/colors.js:35:4
W20160228-19:37:00.245(-5)? (STDERR)     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/boot.js:242:10
W20160228-19:37:00.245(-5)? (STDERR)     at Array.forEach (native)
W20160228-19:37:00.245(-5)? (STDERR)     at Function._.each._.forEach (/Users/kyleking/.meteor/packages/meteor-tool/.1.1.10.1xxe33u++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160228-19:37:00.245(-5)? (STDERR)     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by nooitaf** [comment]
i pushed 0.0.3, maybe that will fix your issue?

**Comment by KyleKing** [comment]
No, unfortunately not, I also tried running meteor from apple terminal as well as iTerm

<img width="720" alt="shell iterm today at 2 06 38 pm" src="https://cloud.githubusercontent.com/assets/3784339/13445726/005c17d4-dfdc-11e5-9d84-2ade744c57fa.png">

The new version did solve the colors value undefined, but didn't help with the colors. Is it possible that the NPM module is never installed?

**Comment by KyleKing** [comment]
Weird, so I deployed my app with mupx (Meteor Up) and the colors were visible in the logs (`mupx logs --tail=50`)?

<img width="526" alt="todo trello google chrome today at 9 05 26 pm" src="https://cloud.githubusercontent.com/assets/3784339/13448468/8a2f36fc-dff1-11e5-8936-c86e0298018c.png">

**Comment by nooitaf** [comment]
ya, i also dont see the rainbow anymore. But i see colors in Terminal(mac). Maybe something changed in how meteor logs to console. 
When i try to update the dependency to the recent 1.1.2 of colors all the colors are gone, no errors, the rest works (.trap), but the colors don't show.

**Comment by nooitaf** [comment]
I just published a new wrapper package that utilizes the `terminal-colors` package. 
It's a way simpler package though. 

https://github.com/nooitaf/meteor-terminal-colors
https://atmospherejs.com/nooitaf/terminal-colors

**Comment by KyleKing** [comment]
Great! I'll give it a try tonight

**Comment by nooitaf** [comment]
Woopp! .....rewind selecta ...  .. i fixed this package here, finally .. xD
![screen shot 2016-03-02 at 20 35 59](https://cloud.githubusercontent.com/assets/1898194/13472747/872b3fe4-e0b6-11e5-9a50-fdde46e7f2f1.jpg)

**Comment by nooitaf** [comment]
BUT .. you have to do `colors.enable = true;` before you will see any colors *facepalm*

**Comment by KyleKing** [comment]
Haha, that is the classic fix for any technology! Glad this issue at least helped the documentation!

I tried the terminal-colors package you just released and it worked! Sort of:
<img width="720" alt="shell iterm today at 9 41 10 pm" src="https://cloud.githubusercontent.com/assets/3784339/13483169/27bb5274-e0c0-11e5-873c-bb4e2845c1ce.png">

I thought it might have to do with a color scheme setting and if I wasn't using the right terminal type, but I am correctly set with the 256 color scheme, so I should see all the colors and not just the basic ones?
<img width="490" alt="preferences iterm today at 9 44 58 pm" src="https://cloud.githubusercontent.com/assets/3784339/13483180/39300cb6-e0c0-11e5-8b8a-a8f21d5d3be9.png">

For completeness, I also attempted running meteor from terminal (Mac):
<img width="1311" alt="meteorapp node node - meteor-packages-meteor-tool- 1 1 10 1xxe33u os osx x86_64 web browser web cordova-mt-os osx x86_64-tools-index js 187x60 terminal today at 9 47 46 pm" src="https://cloud.githubusercontent.com/assets/3784339/13483215/6c68683a-e0c0-11e5-9692-57f8617a073c.png">

It might be my bash profile, but I tried removing anything I customized. Do you know how I could try this out on a *clean* terminal? I don't have access to another mac computer with Meteor installed?

**Comment by nooitaf** [comment]
Sry, i don't know.
I use Terminal.app with xtem-256color and that should work, as i only change colors via terminal settings, not with profiles. I tried to recreate your outcome, but Terminal.app doesn't even have an option to remove underlines and both your terminals show the same "flaw", so I would also guess some dot.config file. 
```text
~/.profile
~/.bashrc
~/.bash_profile
/etc/profile
/etc/bashrc
```

You could try to restore the Defaults.. (it restores all themes)

![screen shot 2016-03-03 at 7 36 14](https://cloud.githubusercontent.com/assets/1898194/13486605/bec82d16-e112-11e5-9008-345d47eed369.jpg)

All my changes that are different from the default are visible on the right side. Font and some checkmarks. Sometimes i give all the colors more brightness but the picture below is with above settings.

![screen shot 2016-03-03 at 8 29 03](https://cloud.githubusercontent.com/assets/1898194/13487416/047ce692-e11a-11e5-8daa-a55d55a7d1ec.jpg)

**Comment by KyleKing** [comment]
Hmm, well I'll play around with it and see if I can get it working. For now the other package works since I have a few colors to play with. Thanks for all of your help!
